name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - dev
    types: [closed]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test # 선택적, 필요시 테스트 실행

      - name: Build project
        run: npm run build

      - name: Push to main
        if: success()
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
